steps:
  - id: 'Start dind'
    name: docker/compose
    args: ['up', '-d' ]
  - id: 'Wait for dind'
    name: 'ubuntu'
    args: [ 'sleep', '200' ]
  - id: 'Check service is listening'
    name: 'gcr.io/cloud-builders/curl'
    args: [ "dind-service:2375" ]
    waitFor: [ 'Wait for dind' ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: ['build', '--network=cloudbuild', '-t', 'gcr.io/$PROJECT_ID/test-container', '.']
    env:
      - 'DOCKER_HOST=tcp://dind-service:2375'