steps:
  - id: 'Start dind'
    name: docker/compose
    args: [ '-f', 'docker-compose.yml', 'up', '-d', 'dind-service' ]
  - name: 'Wait for dind'
    args: [ 'sleep', '200' ]
  - id: 'Check service is listening'
    name: 'gcr.io/cloud-builders/curl'
    args: [ "dind-service:2375" ]
    waitFor: [ 'Start dind' ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: ['build', '--network=cloudbuild', '-t', 'gcr.io/$PROJECT_ID/test-container', '.']
    env:
      - 'DOCKER_HOST=tcp://dind-service:2375'