version: '3'
services:
  dind-service:
    image: docker:dind
    privileged: true
    ports:
      - "127.0.0.1:2375:2375"
      - "127.0.0.1:2376:2376"
    networks:
      - cloudbuild
networks:
  cloudbuild:
      external: true